apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubeenforcer.clusterRoleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubeenforcer.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeenforcer.serviceAccountName" . }}
  namespace: {{ include "kubeenforcer.namespace" . }}
