apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeenforcer.admission-controller.serviceName" . }}
  labels:
    {{- include "kubeenforcer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "kubeenforcer.selectorLabels" . | nindent 4 }}
