apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policyconfigurations.kubescape.io
spec:
  group: kubescape.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            settings:
              type: object
              properties:
                insecureCapabilities:
                  items:
                    type: string
                  type: array
  scope: Cluster
  names:
    plural: policyconfigurations
    singular: policyconfiguration
    kind: PolicyConfiguration